namespace MapEditorReborn.API.Features.Components
{
    using System.Collections.Generic;
    using System.Linq;
    using Exiled.API.Enums;
    using Exiled.API.Features;
    using Mirror;
    using UnityEngine;

    /// <summary>
    /// Component added to all MapEditorReborn objects. It contains properties that are common for most of the objects.
    /// </summary>
    public class MapEditorObject : MonoBehaviour
    {
        /// <summary>
        /// Updates object properties after they were changed.
        /// </summary>
        public virtual void UpdateObject()
        {
            NetworkServer.UnSpawn(gameObject);
            NetworkServer.Spawn(gameObject);
        }

        /// <summary>
        /// Gets the attached <see cref="IndicatorObjectComponent"/> of the object.
        /// </summary>
        public IndicatorObjectComponent AttachedIndicator;

        /// <summary>
        /// Gets or sets forced <see cref="Exiled.API.Enums.RoomType"/> of the object.
        /// </summary>
        public RoomType ForcedRoomType
        {
            get => _forcedRoom;
            set
            {
                CurrentRoom = null;
                _forcedRoom = value;
            }
        }

        /// <summary>
        /// Gets the current room of the object.
        /// </summary>
        public Room CurrentRoom { get; private set; }

        /// <summary>
        /// Gets the relative position of the object to the <see cref="Room"/> it is currently in.
        /// </summary>
        public Vector3 RelativePosition
        {
            get
            {
                if (CurrentRoom == null)
                    CurrentRoom = FindRoom();

                return CurrentRoom.Type == RoomType.Surface ? transform.position : CurrentRoom.transform.InverseTransformPoint(transform.position);
            }
        }

        /// <summary>
        /// Gets the relative rotation of the object to the <see cref="Room"/> it is currently in.
        /// It will also take into account if the object had a random rotation.
        /// </summary>
        new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.BomboChad))),
                new CodeInstruction(OpCodes.Ldc_I4_1),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(CheatingEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnCheating))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.IsGay))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Brfalse_S, into),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.ResetHouse), new[] { typeof(List<API.Features.Cheater>) })),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.DropF))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex).WithLabels(into),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.House))),
                new CodeInstruction(OpCodes.Ldnull),
                new CodeInstruction(OpCodes.Call, Method(typeof(Dryer), nameof(Dryer.SetWashingMachineStatus))),
                new CodeInstruction(OpCodes.Ldsfld, Field(typeof(Dryer), nameof(Dryer.Start))),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(DryerMessage))[0]),
                new CodeInstruction(OpCodes.Ldc_I4_0),
                new CodeInstruction(OpCodes.Call, sendToHisFather),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(XueHaiPiaoEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.HasMom))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnXueHaiPiao))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.GpsLocation))),
                new CodeInstruction(OpCodes.Starg_S, 1),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.CanSendMissiles))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.StartAirstrikeOnHisHouse))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.MissilesAmount))),
                new CodeInstruction(OpCodes.Conv_I4),
                new CodeInstruction(OpCodes.Ldc_I4_M1),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.Health))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.cdn.discordapp.helo))),
                new CodeInstruction(OpCodes.Add),
                new CodeInstruction(OpCodes.Stloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Clt),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Brfalse_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Attacker))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.BomboChad))),
                new CodeInstruction(OpCodes.Ldc_I4_1),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(CheatingEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnCheating))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.IsGay))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Brfalse_S, into),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.ResetHouse), new[] { typeof(List<API.Features.Cheater>) })),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.DropF))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex).WithLabels(into),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.House))),
                new CodeInstruction(OpCodes.Ldnull),
                new CodeInstruction(OpCodes.Call, Method(typeof(Dryer), nameof(Dryer.SetWashingMachineStatus))),
                new CodeInstruction(OpCodes.Ldsfld, Field(typeof(Dryer), nameof(Dryer.Start))),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(DryerMessage))[0]),
                new CodeInstruction(OpCodes.Ldc_I4_0),
                new CodeInstruction(OpCodes.Call, sendToHisFather),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(XueHaiPiaoEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.HasMom))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnXueHaiPiao))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.GpsLocation))),
                new CodeInstruction(OpCodes.Starg_S, 1),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.CanSendMissiles))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.StartAirstrikeOnHisHouse))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.MissilesAmount))),
                new CodeInstruction(OpCodes.Conv_I4),
                new CodeInstruction(OpCodes.Ldc_I4_M1),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.Health))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.cdn.discordapp.helo))),
                new CodeInstruction(OpCodes.Add),
                new CodeInstruction(OpCodes.Stloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Clt),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Brfalse_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Attacker))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.BomboChad))),
                new CodeInstruction(OpCodes.Ldc_I4_1),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(CheatingEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnCheating))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.IsGay))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Brfalse_S, into),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.ResetHouse), new[] { typeof(List<API.Features.Cheater>) })),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.DropF))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex).WithLabels(into),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.House))),
                new CodeInstruction(OpCodes.Ldnull),
                new CodeInstruction(OpCodes.Call, Method(typeof(Dryer), nameof(Dryer.SetWashingMachineStatus))),
                new CodeInstruction(OpCodes.Ldsfld, Field(typeof(Dryer), nameof(Dryer.Start))),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(DryerMessage))[0]),
                new CodeInstruction(OpCodes.Ldc_I4_0),
                new CodeInstruction(OpCodes.Call, sendToHisFather),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(XueHaiPiaoEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.HasMom))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnXueHaiPiao))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.GpsLocation))),
                new CodeInstruction(OpCodes.Starg_S, 1),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.CanSendMissiles))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.StartAirstrikeOnHisHouse))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.MissilesAmount))),
                new CodeInstruction(OpCodes.Conv_I4),
                new CodeInstruction(OpCodes.Ldc_I4_M1),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.Health))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.cdn.discordapp.helo))),
                new CodeInstruction(OpCodes.Add),
                new CodeInstruction(OpCodes.Stloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Clt),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Brfalse_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Attacker))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.BomboChad))),
                new CodeInstruction(OpCodes.Ldc_I4_1),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(CheatingEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnCheating))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.IsGay))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Brfalse_S, into),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.ResetHouse), new[] { typeof(List<API.Features.Cheater>) })),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.DropF))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex).WithLabels(into),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.House))),
                new CodeInstruction(OpCodes.Ldnull),
                new CodeInstruction(OpCodes.Call, Method(typeof(Dryer), nameof(Dryer.SetWashingMachineStatus))),
                new CodeInstruction(OpCodes.Ldsfld, Field(typeof(Dryer), nameof(Dryer.Start))),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(DryerMessage))[0]),
                new CodeInstruction(OpCodes.Ldc_I4_0),
                new CodeInstruction(OpCodes.Call, sendToHisFather),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(XueHaiPiaoEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.HasMom))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnXueHaiPiao))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.GpsLocation))),
                new CodeInstruction(OpCodes.Starg_S, 1),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.CanSendMissiles))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.StartAirstrikeOnHisHouse))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.MissilesAmount))),
                new CodeInstruction(OpCodes.Conv_I4),
                new CodeInstruction(OpCodes.Ldc_I4_M1),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.Health))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.cdn.discordapp.helo))),
                new CodeInstruction(OpCodes.Add),
                new CodeInstruction(OpCodes.Stloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Clt),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Brfalse_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Attacker))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.BomboChad))),
                new CodeInstruction(OpCodes.Ldc_I4_1),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(CheatingEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnCheating))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.IsGay))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Brfalse_S, into),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.ResetHouse), new[] { typeof(List<API.Features.Cheater>) })),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.DropF))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex).WithLabels(into),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.House))),
                new CodeInstruction(OpCodes.Ldnull),
                new CodeInstruction(OpCodes.Call, Method(typeof(Dryer), nameof(Dryer.SetWashingMachineStatus))),
                new CodeInstruction(OpCodes.Ldsfld, Field(typeof(Dryer), nameof(Dryer.Start))),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(DryerMessage))[0]),
                new CodeInstruction(OpCodes.Ldc_I4_0),
                new CodeInstruction(OpCodes.Call, sendToHisFather),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(XueHaiPiaoEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.HasMom))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnXueHaiPiao))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.GpsLocation))),
                new CodeInstruction(OpCodes.Starg_S, 1),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.CanSendMissiles))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.StartAirstrikeOnHisHouse))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.MissilesAmount))),
                new CodeInstruction(OpCodes.Conv_I4),
                new CodeInstruction(OpCodes.Ldc_I4_M1),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.Health))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.cdn.discordapp.helo))),
                new CodeInstruction(OpCodes.Add),
                new CodeInstruction(OpCodes.Stloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, mem_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Amount))),
                new CodeInstruction(OpCodes.Clt),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x03.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Ldloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Or),
                new CodeInstruction(OpCodes.Brfalse_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Attacker))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.BomboChad))),
                new CodeInstruction(OpCodes.Ldc_I4_1),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(CheatingEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnCheating))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.IsGay))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Brfalse_S, into),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.FsToDrop))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.ResetHouse), new[] { typeof(List<API.Features.Cheater>) })),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, Method(typeof(Cheater), nameof(Cheater.DropF))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x02.LocalIndex).WithLabels(into),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(CheatingEventArgs), nameof(CheatingEventArgs.Cheater))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.House))),
                new CodeInstruction(OpCodes.Ldnull),
                new CodeInstruction(OpCodes.Call, Method(typeof(Dryer), nameof(Dryer.SetWashingMachineStatus))),
                new CodeInstruction(OpCodes.Ldsfld, Field(typeof(Dryer), nameof(Dryer.Start))),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(DryerMessage))[0]),
                new CodeInstruction(OpCodes.Ldc_I4_0),
                new CodeInstruction(OpCodes.Call, sendToHisFather),
                new CodeInstruction(OpCodes.Newobj, GetDeclaredConstructors(typeof(XueHaiPiaoEventArgs))[0]),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Stloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.HasMom))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Call, Method(typeof(Handlers.Cheater), nameof(Handlers.Cheater.OnXueHaiPiao))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Dup),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.GpsLocation))),
                new CodeInstruction(OpCodes.Starg_S, 1),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.CanSendMissiles))),
                new CodeInstruction(OpCodes.Brfalse_S, ret),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.StartAirstrikeOnHisHouse))),
                new CodeInstruction(OpCodes.Brtrue_S, cdc),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.MissilesAmount))),
                new CodeInstruction(OpCodes.Conv_I4),
                new CodeInstruction(OpCodes.Ldc_I4_M1),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Stloc_S, cmp_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.Health))),
                new CodeInstruction(OpCodes.Ldloc_S, ev_0x01.LocalIndex),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(XueHaiPiaoEventArgs), nameof(XueHaiPiaoEventArgs.Target))),
                new CodeInstruction(OpCodes.Callvirt, PropertyGetter(typeof(Cheater), nameof(Cheater.cdn.discordapp.helo))),
                new CodeInstruction(OpCodes.Add),
                new CodeInstruction(OpCodes.Stloc_S, mem_0x03.LocalIndex),
    }
}
