### YamlMime:ManagedReference
items:
- uid: MapEditorReborn.Configs.Translation
  commentId: T:MapEditorReborn.Configs.Translation
  id: Translation
  parent: MapEditorReborn.Configs
  children:
  - MapEditorReborn.Configs.Translation.ModeCopying
  - MapEditorReborn.Configs.Translation.ModeCreating
  - MapEditorReborn.Configs.Translation.ModeDeleting
  - MapEditorReborn.Configs.Translation.ModeSelecting
  langs:
  - csharp
  - vb
  name: Translation
  nameWithType: Translation
  fullName: MapEditorReborn.Configs.Translation
  type: Class
  source:
    remote:
      path: C:/Users/minerpl/RiderProjects/MapEditorReborn/Configs/Translation.cs
    id: Translation
    path: Configs/Translation.cs
    startLine: 14
  assemblies:
  - MapEditorReborn
  namespace: MapEditorReborn.Configs
  summary: "\nConfig with translations for the ToolGun.\n"
  example: []
  syntax:
    content: 'public sealed class Translation : ITranslation'
    content.vb: >-
      Public NotInheritable Class Translation
          Inherits ITranslation
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: MapEditorReborn.Configs.Translation.ModeCreating
  commentId: P:MapEditorReborn.Configs.Translation.ModeCreating
  id: ModeCreating
  parent: MapEditorReborn.Configs.Translation
  langs:
  - csharp
  - vb
  name: ModeCreating
  nameWithType: Translation.ModeCreating
  fullName: MapEditorReborn.Configs.Translation.ModeCreating
  type: Property
  source:
    remote:
      path: C:/Users/minerpl/RiderProjects/MapEditorReborn/Configs/Translation.cs
    id: ModeCreating
    path: Configs/Translation.cs
    startLine: 19
  assemblies:
  - MapEditorReborn
  namespace: MapEditorReborn.Configs
  summary: "\nGets a text which represents the creating mode.\n"
  example: []
  syntax:
    content: public string ModeCreating { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property ModeCreating As String
  overload: MapEditorReborn.Configs.Translation.ModeCreating*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: MapEditorReborn.Configs.Translation.ModeDeleting
  commentId: P:MapEditorReborn.Configs.Translation.ModeDeleting
  id: ModeDeleting
  parent: MapEditorReborn.Configs.Translation
  langs:
  - csharp
  - vb
  name: ModeDeleting
  nameWithType: Translation.ModeDeleting
  fullName: MapEditorReborn.Configs.Translation.ModeDeleting
  type: Property
  source:
    remote:
      path: C:/Users/minerpl/RiderProjects/MapEditorReborn/Configs/Translation.cs
    id: ModeDeleting
    path: Configs/Translation.cs
    startLine: 24
  assemblies:
  - MapEditorReborn
  namespace: MapEditorReborn.Configs
  summary: "\nGets a text which represents the deleting mode.\n"
  example: []
  syntax:
    content: public string ModeDeleting { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property ModeDeleting As String
  overload: MapEditorReborn.Configs.Translation.ModeDeleting*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: MapEditorReborn.Configs.Translation.ModeSelecting
  commentId: P:MapEditorReborn.Configs.Translation.ModeSelecting
  id: ModeSelecting
  parent: MapEditorReborn.Configs.Translation
  langs:
  - csharp
  - vb
  name: ModeSelecting
  nameWithType: Translation.ModeSelecting
  fullName: MapEditorReborn.Configs.Translation.ModeSelecting
  type: Property
  source:
    remote:
      path: C:/Users/minerpl/RiderProjects/MapEditorReborn/Configs/Translation.cs
    id: ModeSelecting
    path: Configs/Translation.cs
    startLine: 29
  assemblies:
  - MapEditorReborn
  namespace: MapEditorReborn.Configs
  summary: "\nGets a text which represents the selecting mode.\n"
  example: []
  syntax:
    content: public string ModeSelecting { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property ModeSelecting As String
  overload: MapEditorReborn.Configs.Translation.ModeSelecting*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: MapEditorReborn.Configs.Translation.ModeCopying
  commentId: P:MapEditorReborn.Configs.Translation.ModeCopying
  id: ModeCopying
  parent: MapEditorReborn.Configs.Translation
  langs:
  - csharp
  - vb
  name: ModeCopying
  nameWithType: Translation.ModeCopying
  fullName: MapEditorReborn.Configs.Translation.ModeCopying
  type: Property
  source:
    remote:
      path: C:/Users/minerpl/RiderProjects/MapEditorReborn/Configs/Translation.cs
    id: ModeCopying
    path: Configs/Translation.cs
    startLine: 34
  assemblies:
  - MapEditorReborn
  namespace: MapEditorReborn.Configs
  summary: "\nGets a text which represents the copying mode.\n"
  example: []
  syntax:
    content: public string ModeCopying { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property ModeCopying As String
  overload: MapEditorReborn.Configs.Translation.ModeCopying*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: MapEditorReborn.Configs
  commentId: N:MapEditorReborn.Configs
  name: MapEditorReborn.Configs
  nameWithType: MapEditorReborn.Configs
  fullName: MapEditorReborn.Configs
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: MapEditorReborn.Configs.Translation.ModeCreating*
  commentId: Overload:MapEditorReborn.Configs.Translation.ModeCreating
  name: ModeCreating
  nameWithType: Translation.ModeCreating
  fullName: MapEditorReborn.Configs.Translation.ModeCreating
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: MapEditorReborn.Configs.Translation.ModeDeleting*
  commentId: Overload:MapEditorReborn.Configs.Translation.ModeDeleting
  name: ModeDeleting
  nameWithType: Translation.ModeDeleting
  fullName: MapEditorReborn.Configs.Translation.ModeDeleting
- uid: MapEditorReborn.Configs.Translation.ModeSelecting*
  commentId: Overload:MapEditorReborn.Configs.Translation.ModeSelecting
  name: ModeSelecting
  nameWithType: Translation.ModeSelecting
  fullName: MapEditorReborn.Configs.Translation.ModeSelecting
- uid: MapEditorReborn.Configs.Translation.ModeCopying*
  commentId: Overload:MapEditorReborn.Configs.Translation.ModeCopying
  name: ModeCopying
  nameWithType: Translation.ModeCopying
  fullName: MapEditorReborn.Configs.Translation.ModeCopying
