### YamlMime:ManagedReference
items:
- uid: MapEditorReborn.Configs
  commentId: N:MapEditorReborn.Configs
  id: MapEditorReborn.Configs
  children:
  - MapEditorReborn.Configs.Config
  - MapEditorReborn.Configs.LoadMapOnEvent
  - MapEditorReborn.Configs.Translation
  langs:
  - csharp
  - vb
  name: MapEditorReborn.Configs
  nameWithType: MapEditorReborn.Configs
  fullName: MapEditorReborn.Configs
  type: Namespace
  assemblies:
  - MapEditorReborn
references:
- uid: MapEditorReborn.Configs.LoadMapOnEvent
  commentId: T:MapEditorReborn.Configs.LoadMapOnEvent
  parent: MapEditorReborn.Configs
  name: LoadMapOnEvent
  nameWithType: LoadMapOnEvent
  fullName: MapEditorReborn.Configs.LoadMapOnEvent
- uid: MapEditorReborn.Configs.Config
  commentId: T:MapEditorReborn.Configs.Config
  name: Config
  nameWithType: Config
  fullName: MapEditorReborn.Configs.Config
- uid: MapEditorReborn.Configs.Translation
  commentId: T:MapEditorReborn.Configs.Translation
  name: Translation
  nameWithType: Translation
  fullName: MapEditorReborn.Configs.Translation
- uid: MapEditorReborn.Configs
  commentId: N:MapEditorReborn.Configs
  name: MapEditorReborn.Configs
  nameWithType: MapEditorReborn.Configs
  fullName: MapEditorReborn.Configs
